module.exports = [

	{"name":"Sadda",
	"lowest_price":"350",
	"rating":"4",
	"max_speed":"40mbps",
	"description":"Our Internet plans are now available at never before prices. You can also opt for voice top-up and unlimited local and STD calls from airtel",
	"contact_no":"123456789",
	"email":"info@beam.com",
	"image":"http://via.placeholder.com/350x150",
	"url":"http://www.actcorp.in/personal/fibernet/plans"},
	{"name":"Airtel Telecom",
	"lowest_price":"550",
	"rating":"3.7",
	"max_speed":"40mbps",
	"description":"Our Internet plans are now available at never before prices. You can also opt for voice top-up and unlimited local and STD calls from airtel",
	"contact_no":"123456789",
	"email":"info@airtel.com",
	"image":"http://via.placeholder.com/350x150",
	"url":"http://www.actcorp.in/personal/fibernet/plans"},

	{"name":"Docomo Telecom",
	"lowest_price":"150",
	"rating":"2.2",
	"max_speed":"40mbps",
	"description":"Our Internet plans are now available at never before prices. You can also opt for voice top-up and unlimited local and STD calls from airtel",
	"contact_no":"123456789",
	"email":"info@beam.com",
	"image":"http://via.placeholder.com/350x150",
	"url":"http://www.actcorp.in/personal/fibernet/plans"},

	{"name":"Jio Telecom",
	"lowest_price":"750",
	"rating":"3",
	"max_speed":"40mbps",
	"description":"Our Internet plans are now available at never before prices. You can also opt for voice top-up and unlimited local and STD calls from airtel",
	"contact_no":"123456789",
	"email":"info@beam.com",
	"image":"http://via.placeholder.com/350x150",
	"url":"http://www.actcorp.in/personal/fibernet/plans"},


	{"name":"Idea Telecom",
	"lowest_price":"250",
	"rating":"3.5",
	"max_speed":"40mbps",
	"description":"Our Internet plans are now available at never before prices. You can also opt for voice top-up and unlimited local and STD calls from airtel",
	"contact_no":"123456789",
	"email":"info@idea.com",
	"image":"http://via.placeholder.com/350x150",
	"url":"http://www.actcorp.in/personal/fibernet/plans"},

	{"name":"Airvoice Telecom",
	"lowest_price":"350",
	"rating":"1",
	"max_speed":"40mbps",
	"description":"Our Internet plans are now available at never before prices. You can also opt for voice top-up and unlimited local and STD calls from airtel",
	"contact_no":"123456789",
	"email":"info@airvoice.com",
	"image":"http://via.placeholder.com/350x150",
	"url":"http://www.actcorp.in/personal/fibernet/plans"},

	{"name":"Aircel Telecom",
	"lowest_price":"950",
	"rating":"1.5",
	"max_speed":"40mbps",
	"description":"Our Internet plans are now available at never before prices. You can also opt for voice top-up and unlimited local and STD calls from airtel",
	"contact_no":"123456789",
	"email":"info@aircel.com",
	"image":"http://via.placeholder.com/350x150",
	"url":"http://www.actcorp.in/personal/fibernet/plans"},

	{"name":"BSNL Telecom",
	"lowest_price":"1050",
	"rating":"3",
	"max_speed":"40mbps",
	"description":"Our Internet plans are now available at never before prices. You can also opt for voice top-up and unlimited local and STD calls from airtel",
	"contact_no":"123456789",
	"email":"info@bsnl.com",
	"image":"http://via.placeholder.com/350x150",
	"url":"http://www.actcorp.in/personal/fibernet/plans"},

	{"name":"Virgin Telecom",
	"lowest_price":"850",
	"rating":"3.2",
	"max_speed":"40mbps",
	"description":"Our Internet plans are now available at never before prices. You can also opt for voice top-up and unlimited local and STD calls from airtel",
	"contact_no":"123456789",
	"email":"info@virgin.com",
	"image":"http://via.placeholder.com/350x150",
	"url":"http://www.actcorp.in/personal/fibernet/plans"},

	{"name":"Relience Telecom",
	"lowest_price":"200",
	"rating":"3.5",
	"max_speed":"40mbps",
	"description":"Our Internet plans are now available at never before prices. You can also opt for voice top-up and unlimited local and STD calls from airtel",
	"contact_no":"123456789",
	"email":"info@relience.com",
	"image":"http://via.placeholder.com/350x150",
	"url":"http://www.actcorp.in/personal/fibernet/plans"},

	{"name":"Hathway Telecom",
	"lowest_price":"300",
	"rating":"4",
	"max_speed":"40mbps",
	"description":"Our Internet plans are now available at never before prices. You can also opt for voice top-up and unlimited local and STD calls from airtel",
	"contact_no":"123456789",
	"email":"info@hathway.com",
	"image":"http://via.placeholder.com/350x150",
	"url":"http://www.actcorp.in/personal/fibernet/plans"},

	{"name":"Profilie Telecom",
	"lowest_price":"350",
	"rating":"4.5",
	"max_speed":"40mbps",
	"description":"Our Internet plans are now available at never before prices. You can also opt for voice top-up and unlimited local and STD calls from airtel",
	"contact_no":"123456789",
	"email":"info@telecom.com",
	"image":"http://via.placeholder.com/350x150",
	"url":"http://www.actcorp.in/personal/fibernet/plans"}

]